name: Lint
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  lint:
    # Job name is Greeting
    name: Lint
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: wow-lint
        uses: davidcraig/action-wow-lint@0.1.2
        with:
            path-to-files: '../../src/test.lua'